# Generated by Django 3.0.8 on 2020-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('birth_date', models.DateField(null=True, verbose_name='생년월일')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('country_residence', models.CharField(blank=True, max_length=50, verbose_name='거주국가')),
                ('occupation', models.CharField(blank=True, max_length=50, verbose_name='직업 및 대표경력')),
                ('nationality', models.CharField(blank=True, max_length=20, verbose_name='국적')),
                ('phone_number', models.CharField(blank=True, max_length=25, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='이메일')),
                ('member_level', models.CharField(blank=True, max_length=20, verbose_name='해당여부')),
                ('password', models.CharField(max_length=40, verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': '4050자문위원',
                'verbose_name_plural': '4050자문위원',
            },
        ),
    ]
