# Generated by Django 3.0.8 on 2020-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='닉네임'),
        ),
    ]
