# Generated by Django 3.0.8 on 2020-07-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='글 제목')),
                ('content', models.TextField(blank=True, verbose_name='글내용')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='등록타임')),
                ('post_views', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_counts', models.IntegerField(default=0, verbose_name='좋아요 갯수')),
                ('dislike_counts', models.IntegerField(default=0, verbose_name='싫어요 갯수')),
                ('is_announcement', models.BooleanField(null=True, verbose_name='공지사항?')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '소통실 글',
                'verbose_name_plural': '소통실 글',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community_Post')),
            ],
            options={
                'verbose_name': '소통실 댓글',
            },
        ),
    ]
