# Generated by Django 3.0.8 on 2020-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200716_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_post',
            name='comment_counts',
            field=models.IntegerField(default=0, verbose_name='댓글수'),
        ),
    ]
